---
name: Bug Report
about: Report a problem with Universal Meeting Bridge
title: "[Bug] "
labels: bug
assignees: ''

---

**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:

**Expected behavior**

**Screenshots/Logs**

**Environment (please complete the following):**
 - OS:
 - Node.js version:
 - Meeting platform (Teams/Zoom/Meet):

**Additional context**
